## Basic Function

In [1]:
import numpy as np


In [2]:
a1 = np.array([[1,0.7,3],[4,5,6]], dtype='int32') 
print(a1.shape)
print(a1)

(2, 3)
[[1 0 3]
 [4 5 6]]


In [3]:
a1.shape


(2, 3)

In [4]:
a1.dtype

dtype('int32')

In [5]:
a1 = np.array([[1,2,3,4,5,6],[4,5,6,5,4,3]]) 
print(a1.shape)

(2, 6)


In [6]:
a1.dtype

dtype('int32')

In [7]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(4).dtype

dtype('float64')

In [9]:
np.empty((4,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
a1

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 5, 4, 3]])

In [11]:
a1*a1

array([[ 1,  4,  9, 16, 25, 36],
       [16, 25, 36, 25, 16,  9]])

In [12]:
a1+a1

array([[ 2,  4,  6,  8, 10, 12],
       [ 8, 10, 12, 10,  8,  6]])

In [13]:

a1

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 5, 4, 3]])

In [14]:
a1**a1

array([[    1,     4,    27,   256,  3125, 46656],
       [  256,  3125, 46656,  3125,   256,    27]], dtype=int32)

In [15]:
np.array([6**6])

array([46656])

 # slicing

In [16]:
a =np.array([2,3,4,5,6,7])

In [17]:
arr=a[4:6]

In [18]:
arr

array([6, 7])

In [19]:
arr[0]=9

In [20]:
arr

array([9, 7])

In [21]:
a


array([2, 3, 4, 5, 9, 7])

In [22]:
a =np.array([2,3,4,5,6,7])

In [23]:
arr=a[4:6].copy()

In [24]:
arr[0]=9

In [25]:
arr

array([9, 7])

In [26]:
a

array([2, 3, 4, 5, 6, 7])

In [27]:
a


array([2, 3, 4, 5, 6, 7])

In [28]:
a1

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 5, 4, 3]])

In [29]:
a1[0]

array([1, 2, 3, 4, 5, 6])

In [30]:
a1[0,4]

5