In [1]:
import numpy as np

# arange is faster than range in python

In [2]:
a=np.arange(6)

In [3]:
a


array([0, 1, 2, 3, 4, 5])

In [28]:
b=np.array([1,4,4,5,6,6,21,523,62,26,56,256,45,725,7,47,447,2])
b=b.reshape(6,3)

In [29]:
b

array([[  1,   4,   4],
       [  5,   6,   6],
       [ 21, 523,  62],
       [ 26,  56, 256],
       [ 45, 725,   7],
       [ 47, 447,   2]])

# we can give shape to array

In [30]:
b

array([[  1,   4,   4],
       [  5,   6,   6],
       [ 21, 523,  62],
       [ 26,  56, 256],
       [ 45, 725,   7],
       [ 47, 447,   2]])

# arg sort

In [36]:
    np.argsort(b,axis=0)

array([[0, 0, 5],
       [1, 1, 0],
       [2, 3, 1],
       [3, 5, 4],
       [4, 2, 2],
       [5, 4, 3]], dtype=int32)

In [35]:
np.argmin(b)

0

In [33]:
np.argmax(b)

13